# Generated by Django 4.0.4 on 2022-05-11 18:17

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=gallery.models.gen_post_id, max_length=15, unique=True),
        ),
    ]
